// See https://aka.ms/new-console-template for more information
sbyte firstNumber = -128;
byte secondNumber = 224;
short thirdNumber = 1990;
ushort fourthNumber = 20000;
int fifthNumber = 97;
int sixthNumber = -10000;
sbyte seventhNumber = -115;
byte eightNumber = 112;
int ninethNumber = 52130;
sbyte eleventhNumber = -44;
long twelvethNumber = -1000000;
ulong thirteenthNumber = 970700000;
uint fourthteenthNumber = 4825932;
ulong sixteenthNumber = 123456789123456789;
 Console.Write($"{firstNumber}  {secondNumber} {thirdNumber} {fourthNumber} {fifthNumber} {sixthNumber} {seventhNumber} {eightNumber} {ninethNumber} {eleventhNumber} {twelvethNumber} {thirteenthNumber} {fourthteenthNumber} {sixteenthNumber}");
 Console.WriteLine();
  Console.WriteLine("----------------Question2-------------");
double int1 = 5;
float int2 = -5.02f;
double int3 = 34.56789023;
float int4 = 12.345f;
double int5 =8923.1234857;
decimal int6 = 3456.091124875956542151256683487M;
Console.Write($"{int1}, {int2}, {int3}, {int4}, {int5}, {int6}.");
Console.WriteLine();
Console.WriteLine("-----------Question3---------------");
Console.Write("enter first no: ");
int fisrtNo = int.Parse(Console.ReadLine());
Console.Write("enter second no: ");
int secondNo = int.Parse(Console.ReadLine());
bool precision = Math.Abs(fisrtNo-secondNo) < 0.000001;
Console.WriteLine(precision);
Console.WriteLine("----------------Question4---------------");
int number1 = 256;
Console.WriteLine("the hexadecimal number of 256 is {0:X}",number1);
Console.WriteLine("-------------Question5--------------");
char character = 'L';
Console.WriteLine($"the unicode int is {(int)character}");
Console.WriteLine("--------------Question6---------------");
Console.Write("enter ur gender: ");
bool ismale = true;
Console.WriteLine(ismale);

Console.WriteLine("--------------Question7-----------");
string firstword ="Hello";
string secondword = "World";
object concatenation= firstword + " " + secondword;
Console.WriteLine(concatenation);
Console.WriteLine("------------Question8-------------");
string firststring = "Hello";
string secondstring = "World";
string concat = string.Concat(firststring, secondstring);
object result = concat;
Console.WriteLine(result);
Console.WriteLine("--------------Question9-------------");
Console.WriteLine("\"the \"use\" of quotation marks causes difficulties\"");
Console.WriteLine("\"the use of quotation marks causes difficulties\"");
Console.WriteLine("----------Question10----------");

Console.WriteLine("-------------Question12----------");
string employeename = "Oluwa muhammed";
int age = 21;
string gender ="Male";
decimal emplyoyeenumber = 2756003M;
Console.WriteLine("welcome to MGQS {0}. what's ur age?? i am {1} and also i am {2}\n {3} is ur employee number",employeename,age,gender,emplyoyeenumber);
Console.WriteLine("------------------Question13-----------------");

int a = 5;
int b = 10;

int newA= b;
int newB = a;
Console.WriteLine("{0} and {1}",newA,newB);
